# Generated by Django 2.1.1 on 2018-10-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_name',
        ),
        migrations.AddField(
            model_name='book',
            name='author_surname',
            field=models.CharField(default='Smith', max_length=50),
            preserve_default=False,
        ),
    ]
